use_frameworks!
platform :ios, '13.0'

target 'DiscoverCore_Example' do
  pod 'DiscoverCore', :path => '../'

  target 'DiscoverCore_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
